# Generated by Django 3.2.20 on 2023-08-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapis', '0002_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AlterField(
            model_name='keyvalue',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
